echo bq load --source_format=PARQUET trips_data_all.fhv_test_4 fhv_tripdata_2020-01.parquet
bq load --source_format=PARQUET trips_data_all.fhv_test_4 fhv_tripdata_2020-01.parquet
echo bq load --source_format=PARQUET trips_data_all.fhv_test_4 fhv_tripdata_2020-02.parquet
bq load --source_format=PARQUET trips_data_all.fhv_test_4 fhv_tripdata_2020-02.parquet
echo bq load --source_format=PARQUET trips_data_all.fhv_test_4 fhv_tripdata_2020-03.parquet
bq load --source_format=PARQUET trips_data_all.fhv_test_4 fhv_tripdata_2020-03.parquet
echo bq load --source_format=PARQUET trips_data_all.fhv_test_4 fhv_tripdata_2020-04.parquet
bq load --source_format=PARQUET trips_data_all.fhv_test_4 fhv_tripdata_2020-04.parquet
echo bq load --source_format=PARQUET trips_data_all.fhv_test_4 fhv_tripdata_2020-05.parquet
bq load --source_format=PARQUET trips_data_all.fhv_test_4 fhv_tripdata_2020-05.parquet
echo bq load --source_format=PARQUET trips_data_all.fhv_test_4 fhv_tripdata_2020-06.parquet
bq load --source_format=PARQUET trips_data_all.fhv_test_4 fhv_tripdata_2020-06.parquet
echo bq load --source_format=PARQUET trips_data_all.fhv_test_4 fhv_tripdata_2020-07.parquet
bq load --source_format=PARQUET trips_data_all.fhv_test_4 fhv_tripdata_2020-07.parquet
echo bq load --source_format=PARQUET trips_data_all.fhv_test_4 fhv_tripdata_2020-08.parquet
bq load --source_format=PARQUET trips_data_all.fhv_test_4 fhv_tripdata_2020-08.parquet
echo bq load --source_format=PARQUET trips_data_all.fhv_test_4 fhv_tripdata_2020-09.parquet
bq load --source_format=PARQUET trips_data_all.fhv_test_4 fhv_tripdata_2020-09.parquet
echo bq load --source_format=PARQUET trips_data_all.fhv_test_4 fhv_tripdata_2020-10.parquet
bq load --source_format=PARQUET trips_data_all.fhv_test_4 fhv_tripdata_2020-10.parquet
echo bq load --source_format=PARQUET trips_data_all.fhv_test_4 fhv_tripdata_2020-11.parquet
bq load --source_format=PARQUET trips_data_all.fhv_test_4 fhv_tripdata_2020-11.parquet
echo bq load --source_format=PARQUET trips_data_all.fhv_test_4 fhv_tripdata_2020-12.parquet
bq load --source_format=PARQUET trips_data_all.fhv_test_4 fhv_tripdata_2020-12.parquet
